version: '3'

services:
  nginx-prod: 
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/backend/DRF_Server/static
      - ./nginx:/etc/nginx/conf.d
      - "${EB_LOG_BASE_DIR}/nginx-prod:/var/log/nginx-prod"
    depends_on: 
      - backend
  backend-prod:
    restart: unless-stopped
    build:
      context: ./backend
      args:
        DJANGO_DEVELOPMENT: "false"
      dockerfile: ./Dockerfile 
    entrypoint: ./wsgi-entrypoint.sh
    env_file:
      - .env
    volumes:
      - static_volume:/app/backend/DRF_Server/static
      - "${EB_LOG_BASE_DIR}/DRF-app:/var/log/backend"
    expose:
      - 8000

volumes:
  static_volume: {}
