version: '3'

services:

  nginx: 
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/backend/DRF_Server/static
      - ./nginx:/etc/nginx/conf.d
      - "${EB_LOG_BASE_DIR}/nginx:/var/log/nginx"
    depends_on: 
      - backend

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    entrypoint: ./wsgi-entrypoint.sh
    container_name: backend
    env_file:
      - .env
    volumes:
      - static_volume:/app/backend/DRF_Server/static
      - "${EB_LOG_BASE_DIR}/DRF-app:/var/log/backend"
    expose:
      - 8000

volumes:
  static_volume: {}
